const projects = [
    { id: 1, name: 'PARK MANSION Minami Azabu', image: 'images/project1.jpg', description: 'A luxurious mansion in Minami Azabu.' },
    { id: 2, name: 'with Silence Kawana', image: 'images/project2.jpg', description: 'A tranquil residence in Kawana.' },
    { id: 3, name: 'Park le JADE SHIROKANE Residence', image: 'images/project3.jpg', description: 'A modern residence in Shirokane.' },
    { id: 4, name: 'SEVENS VILLA Karuizawa', image: 'images/project4.jpg', description: 'A beautiful villa in Karuizawa.' },
    { id: 5, name: 'HIKAWA GARDENS', image: 'images/project5.jpg', description: 'Serene gardens in Hikawa.' },
    { id: 6, name: 'ONE AVENUE', image: 'images/project6.jpg', description: 'A stylish avenue development.' },
    { id: 7, name: 'CENTURY FOREST', image: 'images/project7.jpg', description: 'A forest-themed residential area.' },
    { id: 8, name: 'PROUD Rokakoen', image: 'images/project8.jpg', description: 'A proud development in Rokakoen.' },
    { id: 9, name: 'PARK MANSION Roppongi', image: 'images/project9.jpg', description: 'An exclusive mansion in Roppongi.' },
    { id: 10, name: 'NISHIAZABU RESIDENCE', image: 'images/project10.jpg', description: 'A modern residence in Nishiazabu.' },
    { id: 11, name: 'AZABU GARDENS', image: 'images/project11.jpg', description: 'Elegant gardens in Azabu.' },
    { id: 12, name: 'THE PARK HOUSE Gran Minamiaoyama', image: 'images/project12.jpg', description: 'A grand house in Minamiaoyama.' },
    { id: 13, name: 'DIANACOURT Bunkyo Hongodai', image: 'images/project13.jpg', description: 'A courtly residence in Bunkyo Hongodai.' },
    { id: 14, name: 'CLASSY HOUSE Hiroo Fiorire', image: 'images/project14.jpg', description: 'A classy house in Hiroo.' },
    { id: 15, name: 'CLOISTERS Hiroo', image: 'images/project15.jpg', description: 'A cloistered residence in Hiroo.' },
    { id: 16, name: 'F HOUSE', image: 'images/project16.jpg', description: 'A stylish house, model F.' },
    { id: 17, name: 'K HOUSE', image: 'images/project17.jpg', description: 'A modern house, model K.' },
    { id: 18, name: 'INOKASHIRA', image: 'images/project18.jpg', description: 'A beautiful residence in Inokashira.' },
    { id: 19, name: 'ITOHPIA jiyugaoka', image: 'images/project19.jpg', description: 'A modern development in Jiyugaoka.' },
    { id: 20, name: 'ATLAS Suwacho Residence', image: 'images/project20.jpg', description: 'A grand residence in Suwacho.' },
    { id: 21, name: 'Brillia Hongo Sanchome', image: 'images/project21.jpg', description: 'A brilliant residence in Hongo Sanchome.' },
    { id: 22, name: 'FIVE', image: 'images/project22.jpg', description: 'A modern and stylish development.' }
];
